/* Week 02 Agent Log — content carried over VERBATIM from the original homepage section. Do not edit. */
export const week02 = {
  "heading": "Week 02 Agent Log",
  "range": "2026-10-02 to 2026-10-08",
  "task": "Reusable GHL Troubleshooting Skill",
  "agent": "Claude Code · Claude Opus 5.5",
  "type": "AI Agent Building",
  "date": "2026-10-02",
  "status": "built",
  "week": 2,
  "entry": 1,
  "prompt": "Create a reusable GHL Troubleshooting Agent for my LofiStack workflow.\nThe purpose of this agent is to help me troubleshoot real GoHighLevel client issues in a structured and reliable way.\nCore Workflow\nWhen I provide a GHL issue, the agent should:\n\n1. Understand the Issue\n   * Identify what is happening.\n   * Identify what should happen instead.\n   * Summarize the issue clearly before starting the troubleshooting process.\n2. Analyze the Root Cause\n   * Identify the most likely causes.\n   * Review relevant areas such as workflow triggers, conditions, actions, pipelines, custom fields, tags, forms, calendars, integrations, permissions, and other applicable GHL settings.\n   * Clearly separate confirmed information from assumptions.\n3. Provide Troubleshooting Steps\n   * Give me a clear, step-by-step troubleshooting process.\n   * Tell me exactly what to check inside GHL.\n   * Start with the most likely causes.\n   * Avoid unnecessary checks or steps.\n4. Recommend a Fix\n   * Explain the recommended fix clearly.\n   * Provide exact implementation steps whenever possible.\n   * Warn me if the change could affect existing workflows, contacts, pipelines, or automations.\n5. Create a Testing and QA Checklist\n   * Provide a short checklist to use after applying the fix.\n   * Include the exact test scenario.\n   * Explain the expected result.\n   * Help confirm whether the issue has actually been resolved.\n6. Provide a Final Summary\nAt the end, include:\n   * Issue\n   * Root Cause\n   * Fix Applied\n   * Test Result\n   * Remaining Issues\n   * Recommended Next Step\n\nImportant Rules\n\n* Do not invent GHL features, settings, results, or test outcomes.\n* If important information is missing, ask for the required details before reaching a conclusion.\n* Clearly label all assumptions.\n* Do not say an issue is fixed unless it has been tested or verified.\n* Keep the troubleshooting focused on real client work.\n* Use clear, simple language.\n* Avoid unnecessary explanations.\n* If there are multiple possible causes, rank them by likelihood based on the available evidence.\n* Preserve existing working configurations unless there is a clear reason to change them.\n* Prioritize safe changes and explain any possible side effects.\n\nReusability\nMake this agent reusable across different GHL client accounts and issue types, including:\n\n* Workflow problems\n* Trigger issues\n* Automation failures\n* Form submission issues\n* Pipeline problems\n* Custom field issues\n* Tag-related issues\n* Calendar and appointment issues\n* Lead routing\n* Attribution\n* Webhooks and integrations\n* Contact record issues\n* CRM data problems\n* Testing and QA\n\nThe agent should allow me to provide a real GHL problem and receive guidance through the investigation, fix, and verification process."
} as const;
